name: mimir-gael
version: "v3.0.3"
base: core24
summary: Mimir
description: |
  Grafana Mimir is an open source software project that provides a scalable long-term storage for Prometheus.

grade: stable
confinement: strict

platforms:
  amd64:

license: "AGPL-3.0-only"

apps:
  mimir-server:
    command: launchers/mimir-server.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network-observe   # To allow /usr/bin/ip
      - hardware-observe  # To allow /proc/bus/pci/devices
      - network
      - network-bind

  mimir-cli:
    command: launchers/mimir-cli.sh
    plugs:
      - network

parts:
  launchers:
    plugin: dump
    source: snap/local/launchers
    organize:
      'mimir-server.sh' : launchers/
      'mimir-cli.sh' : launchers/
    stage:
      - launchers/mimir-server.sh
      - launchers/mimir-cli.sh

  grafana:
    plugin: dump
    source: https://github.com/grafana/mimir/releases/download/mimir-3.0.3/mimir-3.0.3_amd64.deb
    source-type: deb
